### ISSUE TITLE
Truncate response once on heroku

### ISSUE THREAD

**Issue by clakech** [honeinc/woden#11]
Hello,

I try to use Woden on heroku, thanks for the work!

On localhost everything is ok but once on heroku response begin to be trucated.

Sample:
```
d54
{"test": "sample", "anotherTest":
```
The term "d54" is coming from nowhere. and as you can ses in this sample, the json is truncated.

Do you have any idea to explain why this occurs?

Regards

**Comment by jcblw** [comment]
That is pretty weird. Ill try to set up this server on heroku myself later tonight see if I can see the same issue.

Maybe this is caused by a redirect/proxy on the resource?

**Comment by jcblw** [comment]
hey @clakech

So added an app to heroku.. very simple essentially create the server and then listen. Was able to get a full response. ( There is not error catching here so it may crash  ) :D

https://woden-example.herokuapp.com/?$url=http://img14.deviantart.net/e794/i/2012/334/a/4/phoenix_final07_by_eedenartwork-d5mohzq.jpg

Does not seem to truncate the response on this image.

**Comment by clakech** [comment]
Yes, you are right! I face the exact same problem on your server instance with my API endpoints.

And after trying other JSON API I don't have any problem.

The API I use are not mine, I am just a consumer. I don't know why this does not work.

Thanks for your help.

**Comment by andyburke** [comment]
Can you tell us who owns/where the endpoints are? If we are missing a header or something that would help, that might be a worthwhile addition.

**Comment by clakech** [comment]
Yes but there is a API Key to use (mine). So I can't Copy/Paste this here in public ;-)

May I can send you this info using private message ?

**Comment by andyburke** [comment]
Before you send any API keys, just what service is it? We might be able to hit a test endpoint, for example.

**Comment by clakech** [comment]
I use the rovi TV service: http://prod-doc.rovicorp.com/mashery/index.php/TvListingsRest

**Comment by clakech** [comment]
Trying to debug on heroku with onCache:

```
woden.when( /api.rovicorp.com/, {
	cacheTimeout: function( cacheEntry, req, proxyRes ) {
		if ( proxyRes.statusCode === 404 ) {
			return -1;
		}
		return 1000;
	},
	getKey: function( path, query ) {
		return path;
	},
	onCache: function(cache) {
		zlib.gunzip(cache.body, function (error, result) {
			console.log("error:", error);
			console.log("result:", result);
		});
	}
});
```

output:
```
error: { [Error: incorrect header check] errno: -3, code: 'Z_DATA_ERROR' }
result: undefined
```

On local it works fine!

Seems like the Buffer is not correct, like if we miss a chunk of data or if we have too much chunk of data...

**Comment by clakech** [comment]
FYI I get the exact same strangeness using another node proxy : https://github.com/villadora/express-http-proxy

:disappointed:

**Comment by clakech** [comment]
trying openshift instead of heroku to host the same code and this problem disappears...

**Comment by jcblw** [comment]
@clakech  interesting, must be something heroku is doing thanks for the info
