### ISSUE TITLE
Question: how to proxy/cache a specific domain (regex test)

### ISSUE THREAD

**Issue by dublx** [honeinc/woden#16]
Hi, 
Been trying Woden and follow the readme. 
One thing I dont find to be very explicit in the README is that the woden.when is essentially a plug to customise a specific url pattern. When reading the docs I thought it would only proxy/cache requests which pass the regex test.

How could I have it so that I only proxy/cache a specific regex test, eg /mydomain/, and if for example I get a request with $url=www.example.com Woden does not proxy that request and sends back an appropriate HTTP Code (308 maybe)?

Is that possible?

**Comment by crash83k** [comment]
Hey,

I'd hate to be the bearer of bad news, but this project isn't going to be worked on moving forward. It was created for a project we're using at the moment, but will not be using in the near future. It was created by a dev that no longer works for (or with) Hone Inc. 

At this point, any further development would need to be handled by other devs via forks from this repo. Woden is a cool idea, but we just don't have the time to keep it maintained.

**Comment by dublx** [comment]
Thanks @crash83k
